---
title: "RR-Assignment2"
author: "Laura Florencia"
date: "07/04/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
library(chron)
#py_install("pandas")
```

---

# ASSIGNMENT 2 (for 30/31.03.2022)

Pick a TV show that had its premieres on TV and thus has some viewership numbers reported on Wikipedia.
E.g. [Suits](https://en.wikipedia.org/wiki/List_of_Suits_episodes) (see table just above the References)

Then create a short report (you can copy the content from Wikipedia or other pages for this task) that contains, for example:

(do a commit after each step!)

1. A brief description of the show (use _italics_ for names).
https://en.wikipedia.org/wiki/The_Queen%27s_Gambit_(miniseries)

*The Queen's Gambit* is a 2020 American coming-of-age period drama streaming television miniseries based on the 1983 novel of the same name by *Walter Tevis*. The title refers to the "Queen's Gambit", a chess opening. The series was written and directed by *Scott Frank*, who created it with *Allan Scott*, who owns the rights to the book. Beginning in the mid-1950s and proceeding into the 1960s, the story follows the life of *Beth Harmon (Anya Taylor-Joy)*, a fictional chess prodigy on her rise to the top of the chess world while struggling with drug and alcohol dependency.

Netflix released *The Queen's Gambit* on October 23, 2020. After four weeks it had become Netflix's most-watched scripted miniseries, making it Netflix's top program in 63 countries.[1][2] The series received critical acclaim, with particular praise for *Taylor-Joy's* performance, the cinematography, and production values. It also received a positive response from the chess community for its accurate depictions of high-level chess, and data suggests that it increased public interest in the game.[3][4]

*The Queen's Gambit* won eleven Primetime Emmy Awards, including Outstanding Limited or Anthology Series, becoming the first show on a streaming service to win the category.[5] The series also won two Golden Globe Awards: Best Limited Series or Television Film and Best Actress – Miniseries or Television Film for *Taylor-Joy*. She also won the Screen Actors Guild Award for Outstanding Performance by a Female Actor in a Miniseries or Television Movie.

2. A photo with the logo or a shot from the show itself.

3. A summary of some basic statistics (e.g. on viewership or ratings).

4. A graph of the viewership over time.

5. A graph of the episode-to-episode (or season-to-season) changes in viewership.

6. A short description of the observed changes that includes inline references to numbers (e.g. the viewership decreased by `insert_calculated_number` between seasons 3 and 5).

7. Make sure your report looks nice -> this time we're mostly interested in the output and not necessarily the codes used to achieve it.
7. `knitr` your report and save it in the relevant folder (RR_Mar_30_31) of your repo. 
8. Commit the changes and push them to Github.

### Some other chunk options

E.g.:

- `highlight` -- syntax coloring

- `tidy`-- clean and format the code based on, e.g. `formatR` or `styler`, with specific options defined by `tidy.opts`

For chunks with figures, e.g.:

- `fig.align` -- alignment

- `fig.ext` -- image format

- `dev` -- graphical device for the plot generation

- `dev.args`-- arguments to be passed to device (e.g. for image customisation)

- `dpi` -- DPI

You can, e.g., combine the above to produce images in DPI resolution and format appropriate for a publication.
